name: Node CI
#The action that trigger the jobs
on: [push]

jobs:
  build:
#    The system image we will work on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
#    The diffents steps
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
#   The step where we launch the tests
    - name: npm install and test
      run: |
        npm ci
        npm test
      env:
        CI: true
